-- Friend Locator Script
-- Generated by Jules

local Players = game:GetService("Players")
local CoreGui = game:GetService("CoreGui")
local HttpService = game:GetService("HttpService")
local UserInputService = game:GetService("UserInputService")
local RunService = game:GetService("RunService")

-- Configuration
local CONFIG_FILE = "friend_tracker_config.json"

local Config = {
    Friends = {}, -- List of usernames
    Settings = {
        AutoActivate = false,
        HideUntilFound = false,
        VisualsEnabled = true,
        ShowName = true,
        ShowDistance = true,
        Colors = {
            Text = {R = 255, G = 255, B = 255},
            Background = {R = 0, G = 0, B = 0} -- For labels if needed
        },
        ButtonPosition = {X = 1, Y = 0, OffsetX = -50, OffsetY = 50} -- Default Top Right-ish
    }
}

-- Helper: Deep Copy Table
local function deepCopy(orig)
    local original_type = type(orig)
    local copy
    if original_type == 'table' then
        copy = {}
        for original_key, original_value in next, orig, nil do
            copy[deepCopy(original_key)] = deepCopy(original_value)
        end
        setmetatable(copy, deepCopy(getmetatable(orig)))
    else -- number, string, boolean, etc
        copy = orig
    end
    return copy
end

-- File System Logic
local function SaveConfig()
    local success, json = pcall(function()
        return HttpService:JSONEncode(Config)
    end)

    if success then
        if writefile then
            writefile(CONFIG_FILE, json)
            print("Friend Locator: Config saved.")
        else
            warn("Friend Locator: writefile not supported on this executor.")
        end
    else
        warn("Friend Locator: Failed to encode config.")
    end
end

local function LoadConfig()
    if isfile and isfile(CONFIG_FILE) then
        local success, content = pcall(function()
            return readfile(CONFIG_FILE)
        end)

        if success and content then
            local decodedSuccess, decoded = pcall(function()
                return HttpService:JSONDecode(content)
            end)

            if decodedSuccess and decoded then
                -- Merge loaded config with defaults to ensure new settings exist
                -- Simple merge: overwrite defaults with loaded values
                if decoded.Friends then Config.Friends = decoded.Friends end
                if decoded.Settings then
                    for k, v in pairs(decoded.Settings) do
                        Config.Settings[k] = v
                    end
                end
                print("Friend Locator: Config loaded.")
                return true
            end
        end
    end
    return false
end

-- Initial Load
local configLoaded = LoadConfig()

-- Globals for UI
local ScreenGui = nil
local OnboardingFrame = nil
local MainHUD = nil
local FriendVisuals = {}

-- UI Library (Mini)
local UILib = {}

function UILib.CreateScreenGui()
    local gui = Instance.new("ScreenGui")
    gui.Name = "FriendLocatorUI"
    gui.ResetOnSpawn = false
    -- Try to parent to CoreGui for security, fallback to PlayerGui
    pcall(function()
        gui.Parent = CoreGui
    end)
    if not gui.Parent then
        gui.Parent = Players.LocalPlayer:WaitForChild("PlayerGui")
    end
    return gui
end

function UILib.CreateFrame(props)
    local frame = Instance.new("Frame")
    frame.BorderSizePixel = 0
    frame.BackgroundColor3 = Color3.fromRGB(40, 40, 40) -- Dark theme
    for k, v in pairs(props) do
        frame[k] = v
    end
    return frame
end

function UILib.CreateLabel(props)
    local label = Instance.new("TextLabel")
    label.BackgroundTransparency = 1
    label.TextColor3 = Color3.fromRGB(255, 255, 255)
    label.Font = Enum.Font.Gotham
    label.TextSize = 14
    for k, v in pairs(props) do
        label[k] = v
    end
    return label
end

function UILib.CreateButton(props)
    local button = Instance.new("TextButton")
    button.BorderSizePixel = 0
    button.BackgroundColor3 = Color3.fromRGB(60, 60, 60)
    button.TextColor3 = Color3.fromRGB(255, 255, 255)
    button.Font = Enum.Font.GothamBold
    button.TextSize = 14
    button.AutoButtonColor = true

    -- Rounded corners by default for buttons
    local corner = Instance.new("UICorner")
    corner.CornerRadius = UDim.new(0, 6)
    corner.Parent = button

    for k, v in pairs(props) do
        button[k] = v
    end
    return button
end

function UILib.CreateTextBox(props)
    local box = Instance.new("TextBox")
    box.BorderSizePixel = 0
    box.BackgroundColor3 = Color3.fromRGB(30, 30, 30)
    box.TextColor3 = Color3.fromRGB(255, 255, 255)
    box.PlaceholderColor3 = Color3.fromRGB(150, 150, 150)
    box.Font = Enum.Font.Gotham
    box.TextSize = 14
    box.ClearTextOnFocus = false

    local corner = Instance.new("UICorner")
    corner.CornerRadius = UDim.new(0, 6)
    corner.Parent = box

    for k, v in pairs(props) do
        box[k] = v
    end
    return box
end

function UILib.CreateScrollingFrame(props)
    local scroll = Instance.new("ScrollingFrame")
    scroll.BorderSizePixel = 0
    scroll.BackgroundColor3 = Color3.fromRGB(35, 35, 35)
    scroll.ScrollBarThickness = 6
    scroll.ScrollBarImageColor3 = Color3.fromRGB(100, 100, 100)
    for k, v in pairs(props) do
        scroll[k] = v
    end
    return scroll
end

-- Main Entry Point
ScreenGui = UILib.CreateScreenGui()

-- Onboarding Logic
local function CreateOnboarding()
    local frame = UILib.CreateFrame({
        Parent = ScreenGui,
        Size = UDim2.new(0, 400, 0, 350),
        Position = UDim2.new(0.5, -200, 0.5, -175),
        Name = "OnboardingFrame"
    })

    local corner = Instance.new("UICorner")
    corner.CornerRadius = UDim.new(0, 12)
    corner.Parent = frame

    -- Title
    UILib.CreateLabel({
        Parent = frame,
        Text = "Who's your Friend?",
        Size = UDim2.new(1, 0, 0, 40),
        Position = UDim2.new(0, 0, 0, 10),
        TextSize = 20,
        Font = Enum.Font.GothamBold
    })

    -- Input
    local inputField = UILib.CreateTextBox({
        Parent = frame,
        Size = UDim2.new(0.7, -20, 0, 40),
        Position = UDim2.new(0, 10, 0, 60),
        PlaceholderText = "Input Username (full)"
    })

    local addButton = UILib.CreateButton({
        Parent = frame,
        Text = "+",
        Size = UDim2.new(0.3, -10, 0, 40),
        Position = UDim2.new(0.7, 0, 0, 60),
        BackgroundColor3 = Color3.fromRGB(0, 170, 255)
    })

    -- Notification Label
    local notifLabel = UILib.CreateLabel({
        Parent = frame,
        Text = "",
        Size = UDim2.new(1, 0, 0, 20),
        Position = UDim2.new(0, 0, 0, 105),
        TextTransparency = 1,
        TextColor3 = Color3.fromRGB(100, 255, 100)
    })

    -- Friend List
    local friendList = UILib.CreateScrollingFrame({
        Parent = frame,
        Size = UDim2.new(1, -20, 0, 150),
        Position = UDim2.new(0, 10, 0, 130),
        CanvasSize = UDim2.new(0, 0, 0, 0)
    })

    local listLayout = Instance.new("UIListLayout")
    listLayout.Parent = friendList
    listLayout.SortOrder = Enum.SortOrder.LayoutOrder
    listLayout.Padding = UDim.new(0, 5)

    local function updateFriendList()
        -- Clear
        for _, child in ipairs(friendList:GetChildren()) do
            if child:IsA("Frame") then child:Destroy() end
        end

        for i, name in ipairs(Config.Friends) do
            local row = UILib.CreateFrame({
                Parent = friendList,
                Size = UDim2.new(1, 0, 0, 30),
                BackgroundColor3 = Color3.fromRGB(50, 50, 50)
            })

            local rowCorner = Instance.new("UICorner")
            rowCorner.CornerRadius = UDim.new(0, 4)
            rowCorner.Parent = row

            UILib.CreateLabel({
                Parent = row,
                Text = name,
                Size = UDim2.new(0.8, 0, 1, 0),
                Position = UDim2.new(0, 10, 0, 0),
                TextXAlignment = Enum.TextXAlignment.Left
            })

            local removeBtn = UILib.CreateButton({
                Parent = row,
                Text = "X",
                Size = UDim2.new(0, 20, 0, 20),
                Position = UDim2.new(1, -25, 0.5, -10),
                BackgroundColor3 = Color3.fromRGB(200, 50, 50),
                TextSize = 12
            })

            removeBtn.MouseButton1Click:Connect(function()
                table.remove(Config.Friends, i)
                updateFriendList()
                -- Notification
                notifLabel.Text = "Friend Removed"
                notifLabel.TextColor3 = Color3.fromRGB(255, 80, 80)
                notifLabel.TextTransparency = 0
                task.delay(2, function() notifLabel.TextTransparency = 1 end)
            end)
        end
        friendList.CanvasSize = UDim2.new(0, 0, 0, #Config.Friends * 35)
    end

    -- Add Logic
    addButton.MouseButton1Click:Connect(function()
        local name = inputField.Text
        if name and #name > 0 then
            -- Basic duplicate check
            local exists = false
            for _, v in ipairs(Config.Friends) do
                if v:lower() == name:lower() then exists = true break end
            end

            if not exists then
                table.insert(Config.Friends, name)
                inputField.Text = ""
                updateFriendList()

                notifLabel.Text = "Friend Saved"
                notifLabel.TextColor3 = Color3.fromRGB(100, 255, 100)
                notifLabel.TextTransparency = 0
                task.delay(2, function() notifLabel.TextTransparency = 1 end)
            else
                notifLabel.Text = "Already in list"
                notifLabel.TextColor3 = Color3.fromRGB(255, 200, 50)
                notifLabel.TextTransparency = 0
                task.delay(2, function() notifLabel.TextTransparency = 1 end)
            end
        end
    end)

    updateFriendList()

    -- Continue Button
    local continueBtn = UILib.CreateButton({
        Parent = frame,
        Text = "Continue",
        Size = UDim2.new(0.8, 0, 0, 40),
        Position = UDim2.new(0.1, 0, 0.85, 0),
        BackgroundColor3 = Color3.fromRGB(0, 200, 100)
    })

    return frame, continueBtn
end

-- Main HUD Logic
local function CreateMainHUD()
    -- Settings Button
    local settingsBtn = UILib.CreateButton({
        Parent = ScreenGui,
        Text = "Settings",
        Size = UDim2.new(0, 80, 0, 30),
        Position = UDim2.new(Config.Settings.ButtonPosition.X, Config.Settings.ButtonPosition.OffsetX, Config.Settings.ButtonPosition.Y, Config.Settings.ButtonPosition.OffsetY),
        BackgroundColor3 = Color3.fromRGB(40, 40, 40)
    })

    -- Mobile Drag Logic
    local dragging = false
    local dragStart = nil
    local startPos = nil
    local holdStart = 0

    settingsBtn.InputBegan:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
            holdStart = tick()
            dragStart = input.Position
            startPos = settingsBtn.Position

            -- Wait for hold (0.5s) or move
            local connection
            connection = RunService.RenderStepped:Connect(function()
                if not dragStart then connection:Disconnect() return end

                if tick() - holdStart >= 0.5 then
                    dragging = true
                    settingsBtn.BackgroundColor3 = Color3.fromRGB(80, 80, 80) -- Visual feedback
                    connection:Disconnect()
                end
            end)

            -- Cleanup if released early
            input.Changed:Connect(function()
                if input.UserInputState == Enum.UserInputState.End then
                    dragStart = nil
                    if connection then connection:Disconnect() end
                    if dragging then
                        dragging = false
                        settingsBtn.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
                        -- Save position
                        Config.Settings.ButtonPosition.X = settingsBtn.Position.X.Scale
                        Config.Settings.ButtonPosition.OffsetX = settingsBtn.Position.X.Offset
                        Config.Settings.ButtonPosition.Y = settingsBtn.Position.Y.Scale
                        Config.Settings.ButtonPosition.OffsetY = settingsBtn.Position.Y.Offset
                        SaveConfig()
                    end
                end
            end)
        end
    end)

    UserInputService.InputChanged:Connect(function(input)
        if dragging and (input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch) then
            local delta = input.Position - dragStart
            local newX = startPos.X.Offset + delta.X
            local newY = startPos.Y.Offset + delta.Y

            -- Basic clamp to screen
            local viewportSize = ScreenGui.AbsoluteSize
            if startPos.X.Scale == 1 then newX = math.clamp(newX, -viewportSize.X, 0) end -- Simple logic fix needed for perfect clamping, but acceptable for now

            settingsBtn.Position = UDim2.new(startPos.X.Scale, newX, startPos.Y.Scale, newY)
        end
    end)

    -- Settings Menu
    local settingsFrame = UILib.CreateFrame({
        Parent = ScreenGui,
        Size = UDim2.new(0, 300, 0, 450),
        Position = UDim2.new(0.5, -150, 0.5, -225),
        Name = "SettingsFrame",
        Visible = false
    })
    local corner = Instance.new("UICorner"); corner.Parent = settingsFrame; corner.CornerRadius = UDim.new(0,10)

    UILib.CreateLabel({
        Parent = settingsFrame,
        Text = "Settings",
        Size = UDim2.new(1, 0, 0, 40),
        Position = UDim2.new(0, 0, 0, 5),
        TextSize = 18,
        Font = Enum.Font.GothamBold
    })

    local closeBtn = UILib.CreateButton({
        Parent = settingsFrame,
        Text = "X",
        Size = UDim2.new(0, 30, 0, 30),
        Position = UDim2.new(1, -35, 0, 5),
        BackgroundColor3 = Color3.fromRGB(200, 50, 50)
    })
    closeBtn.MouseButton1Click:Connect(function() settingsFrame.Visible = false end)

    settingsBtn.MouseButton1Click:Connect(function()
        if not dragging then
            settingsFrame.Visible = not settingsFrame.Visible
        end
    end)

    -- Settings Content Scroll
    local contentList = UILib.CreateScrollingFrame({
        Parent = settingsFrame,
        Size = UDim2.new(1, -20, 1, -50),
        Position = UDim2.new(0, 10, 0, 45),
        CanvasSize = UDim2.new(0, 0, 0, 500)
    })
    local layout = Instance.new("UIListLayout"); layout.Parent = contentList; layout.Padding = UDim.new(0, 10); layout.SortOrder = Enum.SortOrder.LayoutOrder

    local function CreateToggle(text, configKey)
        local frame = UILib.CreateFrame({ Parent = contentList, Size = UDim2.new(1, 0, 0, 40), BackgroundTransparency = 1 })
        UILib.CreateLabel({ Parent = frame, Text = text, Size = UDim2.new(0.7, 0, 1, 0), TextXAlignment = Enum.TextXAlignment.Left })
        local btn = UILib.CreateButton({
            Parent = frame,
            Text = Config.Settings[configKey] and "ON" or "OFF",
            Size = UDim2.new(0.3, 0, 0.8, 0),
            Position = UDim2.new(0.7, 0, 0.1, 0),
            BackgroundColor3 = Config.Settings[configKey] and Color3.fromRGB(0, 200, 100) or Color3.fromRGB(200, 50, 50)
        })
        btn.MouseButton1Click:Connect(function()
            Config.Settings[configKey] = not Config.Settings[configKey]
            btn.Text = Config.Settings[configKey] and "ON" or "OFF"
            btn.BackgroundColor3 = Config.Settings[configKey] and Color3.fromRGB(0, 200, 100) or Color3.fromRGB(200, 50, 50)
            SaveConfig()
        end)
    end

    CreateToggle("Visuals Enabled", "VisualsEnabled")
    CreateToggle("Show Name", "ShowName")
    CreateToggle("Show Distance", "ShowDistance")
    CreateToggle("Hide Until Found", "HideUntilFound")
    CreateToggle("Auto-Activate", "AutoActivate")

    -- Color Settings
    local colorFrame = UILib.CreateFrame({ Parent = contentList, Size = UDim2.new(1, 0, 0, 80), BackgroundTransparency = 1 })
    UILib.CreateLabel({ Parent = colorFrame, Text = "Text Color (RGB)", Size = UDim2.new(1, 0, 0, 20), TextXAlignment = Enum.TextXAlignment.Left })

    local rInput = UILib.CreateTextBox({ Parent = colorFrame, Size = UDim2.new(0.3, -5, 0, 30), Position = UDim2.new(0, 0, 0, 25), Text = tostring(Config.Settings.Colors.Text.R), PlaceholderText = "R" })
    local gInput = UILib.CreateTextBox({ Parent = colorFrame, Size = UDim2.new(0.3, -5, 0, 30), Position = UDim2.new(0.33, 0, 0, 25), Text = tostring(Config.Settings.Colors.Text.G), PlaceholderText = "G" })
    local bInput = UILib.CreateTextBox({ Parent = colorFrame, Size = UDim2.new(0.3, -5, 0, 30), Position = UDim2.new(0.66, 0, 0, 25), Text = tostring(Config.Settings.Colors.Text.B), PlaceholderText = "B" })

    local function UpdateColor()
        local r, g, b = tonumber(rInput.Text), tonumber(gInput.Text), tonumber(bInput.Text)
        if r and g and b then
            Config.Settings.Colors.Text = {R = math.clamp(r,0,255), G = math.clamp(g,0,255), B = math.clamp(b,0,255)}
            SaveConfig()
        end
    end
    rInput.FocusLost:Connect(UpdateColor)
    gInput.FocusLost:Connect(UpdateColor)
    bInput.FocusLost:Connect(UpdateColor)

    -- Manage Friends Button in Settings
    local manageBtn = UILib.CreateButton({
        Parent = contentList,
        Text = "Manage Friends",
        Size = UDim2.new(1, 0, 0, 40),
        BackgroundColor3 = Color3.fromRGB(0, 150, 255)
    })
    manageBtn.MouseButton1Click:Connect(function()
        -- Simple hack: Show onboarding again but modify it slightly or just re-use it
        settingsFrame.Visible = false
        OnboardingFrame.Visible = true
    end)

    return {SettingsBtn = settingsBtn, SettingsFrame = settingsFrame}
end

-- Friend Logic & Visuals
local function UpdateVisuals()
    if not Config.Settings.VisualsEnabled then
        for _, v in pairs(FriendVisuals) do v:Destroy() end
        FriendVisuals = {}
        return
    end

    -- Clean up invalid visuals
    for name, bill in pairs(FriendVisuals) do
        if not Players:FindFirstChild(name) then
            bill:Destroy()
            FriendVisuals[name] = nil
        end
    end

    local localPlayer = Players.LocalPlayer
    if not localPlayer or not localPlayer.Character or not localPlayer.Character:FindFirstChild("HumanoidRootPart") then return end

    local friendsFound = false

    for _, player in ipairs(Players:GetPlayers()) do
        if player ~= localPlayer then
            local isFriend = false
            for _, friendName in ipairs(Config.Friends) do
                if player.Name:lower() == friendName:lower() then
                    isFriend = true
                    break
                end
            end

            if isFriend then
                friendsFound = true
                if player.Character and player.Character:FindFirstChild("Head") then
                    local head = player.Character.Head

                    -- Create or Update Billboard
                    local bill = FriendVisuals[player.Name]
                    if not bill then
                        bill = Instance.new("BillboardGui")
                        bill.Name = "FriendVisual_" .. player.Name
                        bill.Adornee = head
                        bill.Size = UDim2.new(0, 200, 0, 50)
                        bill.StudsOffset = Vector3.new(0, 2, 0)
                        bill.AlwaysOnTop = true
                        bill.Parent = ScreenGui.Parent -- Parent to CoreGui/PlayerGui for correct 3D rendering

                        local label = Instance.new("TextLabel")
                        label.Parent = bill
                        label.Size = UDim2.new(1, 0, 1, 0)
                        label.BackgroundTransparency = 1
                        label.Font = Enum.Font.GothamBold
                        label.TextStrokeTransparency = 0.5
                        label.TextStrokeColor3 = Color3.new(0, 0, 0)

                        FriendVisuals[player.Name] = bill
                    end

                    -- Update Content
                    local dist = math.floor((localPlayer.Character.HumanoidRootPart.Position - head.Position).Magnitude)
                    local text = ""
                    if Config.Settings.ShowName then text = text .. player.Name .. "\n" end
                    if Config.Settings.ShowDistance then text = text .. "[" .. dist .. "m]" end

                    local label = bill:FindFirstChild("TextLabel")
                    if label then
                        label.Text = text
                        local c = Config.Settings.Colors.Text
                        label.TextColor3 = Color3.fromRGB(c.R, c.G, c.B)
                    end
                else
                    -- Character missing, remove visual temporarily
                    if FriendVisuals[player.Name] then
                        FriendVisuals[player.Name]:Destroy()
                        FriendVisuals[player.Name] = nil
                    end
                end
            end
        end
    end

    -- "Hide Until Found" Logic
    if Config.Settings.HideUntilFound then
        if MainHUD and MainHUD.SettingsBtn then
             -- If friends are found, show button (if it was hidden).
             -- If no friends found, hide button.
             -- BUT, we need to ensure we don't hide it if the user is interacting or if visuals are disabled but they want to change settings.
             -- The requirement: "keeps UI hidden until a friend joins".
             MainHUD.SettingsBtn.Visible = friendsFound
        end
    else
        if MainHUD and MainHUD.SettingsBtn then
            MainHUD.SettingsBtn.Visible = true
        end
    end
end

-- Setup Loops and Events
local isTrackerRunning = false

local function StartFriendTracker()
    if isTrackerRunning then return end
    isTrackerRunning = true

    -- Loop for visuals (High refresh rate for distance)
    RunService.RenderStepped:Connect(function()
        UpdateVisuals()
    end)

    -- Slower loop for scanning (redundancy, though RenderStepped handles it well)
    task.spawn(function()
        while true do
            task.wait(1)
            -- Could do a heavier check here if needed, but RenderStepped covers it.
            -- Maybe check for "Hide Until Found" visibility here to be safe.
        end
    end)

    -- Events
    Players.PlayerAdded:Connect(function(player)
        -- Immediate check if friend
        local isFriend = false
        for _, friendName in ipairs(Config.Friends) do
            if player.Name:lower() == friendName:lower() then
                isFriend = true
                break
            end
        end

        if isFriend then
            -- Trigger immediate visual update or notification
            -- For now, UpdateVisuals on next frame handles it, but we could send a notification here if we had a notification system
            -- Since we need to verify it works "in addition to the loop", checking immediately ensures no delay
            task.wait(0.5) -- Wait for character load potentially
            UpdateVisuals()
        end
    end)
end

-- Initialize Flow
local function Init()
    OnboardingFrame, ContinueBtn = CreateOnboarding()
    MainHUD = CreateMainHUD()

    -- Connect Continue Button
    ContinueBtn.MouseButton1Click:Connect(function()
        OnboardingFrame.Visible = false
        -- MainHUD.SettingsFrame.Visible = false -- Start hidden
        SaveConfig()

        if not isTrackerRunning then
            StartFriendTracker()
        end

        -- If returning from "Manage Friends", we might want to ensure HUD button visibility is correct
        UpdateVisuals()
    end)

    -- Check Auto-Activate
    if configLoaded and Config.Settings.AutoActivate then
        print("Friend Locator: Auto-Activating...")
        OnboardingFrame.Visible = false
        StartFriendTracker()
    else
        OnboardingFrame.Visible = true
        MainHUD.SettingsBtn.Visible = false -- Hide HUD during onboarding
    end
end

Init()
